qs = [
  { content: "What's the cool online learning site?", answer: 'Quipper' },
  { content: 'How many letters are there in the English alphabet?', answer: '26' },
  { content: "What number is 'A' in the alphabet?", answer: '1' },
  { content: "What number is 'B' in the alphabet?", answer: '2' },
  { content: "What number is 'C' in the alphabet?", answer: '3' },
  { content: "What number is 'D' in the alphabet?", answer: '4' },
  { content: "What number is 'E' in the alphabet?", answer: '5' },
  { content: "What number is 'F' in the alphabet?", answer: '6' },
  { content: "What number is 'G' in the alphabet?", answer: '7' },
  { content: "What number is 'H' in the alphabet?", answer: '8' },
  { content: "What number is 'I' in the alphabet?", answer: '9' },
  { content: "What number is 'J' in the alphabet?", answer: '10' },
  { content: "What number is 'K' in the alphabet?", answer: '11' },
  { content: "What number is 'L' in the alphabet?", answer: '12' },
  { content: "What number is 'M' in the alphabet?", answer: '13' },
  { content: "What number is 'N' in the alphabet?", answer: '14' },
  { content: "What number is 'O' in the alphabet?", answer: '15' },
  { content: "What number is 'P' in the alphabet?", answer: '16' },
  { content: "What number is 'Q' in the alphabet?", answer: '17' },
  { content: "What number is 'R' in the alphabet?", answer: '18' },
  { content: "What number is 'S' in the alphabet?", answer: '19' },
  { content: "What number is 'T' in the alphabet?", answer: '20' },
  { content: "What number is 'U' in the alphabet?", answer: '21' },
  { content: "What number is 'V' in the alphabet?", answer: '22' },
  { content: "What number is 'W' in the alphabet?", answer: '23' },
  { content: "What number is 'X' in the alphabet?", answer: '24' },
  { content: "What number is 'Y' in the alphabet?", answer: '25' },
  { content: "What number is 'Z' in the alphabet?", answer: '26' },
]
qs.each { |q| Question.create(q) }
